Project 3: Part 1A
transistasis/PFMCPP_Project3 pull request #1
Opened 2021-07-15 02:17 UTC by transistasis

In this pull request:
* Finished updating the necessary fields for Part 1A

2021-07-15 04:24 UTC, matkatmusic approved these changes

2021-07-21 05:52 UTC, matkatmusic approved these changes

2021-07-22 09:37 UTC, matkatmusic approved these changes

2021-07-23 22:36 UTC, matkatmusic approved these changes

2021-07-25 04:13 UTC, matkatmusic requested changes

2021-07-25 04:13 UTC, matkatmusic commented on main.cpp
> +    struct MotorcycleOperatingState
you don't need the word `Motorcycle` in this type name.  the fully qualified name will be 
`Motorcycle::OperatingState`.  as you can see, putting `Motorcycle` in the nested name is redundant.
- [ ] revise

2021-07-25 04:23 UTC, transistasis commented on main.cpp
> +    struct MotorcycleOperatingState
Thanks, I'll keep this in mind in the future! Fixed.

2021-07-25 04:57 UTC, matkatmusic approved these changes

2021-07-25 04:58 UTC, merged