Project 3 - Part 2 Development Branch
transistasis/PFMCPP_Project3 pull request #2
Opened 2021-07-27 05:42 UTC by transistasis

In this pull request:

* Finished writing the required function implementations
* Verified that there are no compiler errors or warnings

2021-07-27 07:57 UTC, matkatmusic requested changes

2021-07-27 07:57 UTC, matkatmusic commented on main.cpp
> +}
Spaces are not automatically added when you use `<<`
you might expect to see this:
```
Broadcasting the note on message 0x9 2 65 114
```
but what you'll actually see is:
```
Broadcasting the note on message 0x9265114
```
you can add spaces like this:
```
std::cout << "text" << numbers << " " << moreNumbers << std::endl;
```
- [ ] revise

2021-07-27 07:57 UTC, matkatmusic commented on main.cpp
> +    };
`sizeOfStep` needs an initial value.  you're returning it in `stepSize()` but because you haven't initialized it, the value being returned will be whatever value was held at the memory address `sizeOfStep` is currently occupying.  AKA Garbage!
- [ ] revise

2021-07-27 07:57 UTC, matkatmusic commented on main.cpp
> +}
If you find yourself writing code like this:
```
int Type::someFunction()
{
    if( someExpression )
    {
        someStatement();
        return aValue;
    } 
    else 
    {
        return anotherValue;
    }
}
```
When the `if()` block is entered, the `return aValue;` is the last line of code to be executed.
you have no code after the `else` block that needs executing, since your `else` block contains a `return` statement.
`return` statements are the last thing that **ever happens** in a function
That means if your `if()` block is **NOT** entered, it will be skipped.  What is the next thing that happens?  `return anotherValue;`
that means you do **NOT** need the else block, and it is just causing visual clutter.
```
int Type::someFunction()
{
    if( someExpression )
    {
        someStatement();
        return aValue;
    } 
    return anotherValue;
}
```
Furthermore, you can use a ternary expression:
```
return (condition ? trueResult : falseResult );
```
which would look like this:
```
return (activeLowOutput ? !spectrumAnalyzerDisplayEnabled : spectrumAnalyzerDisplayEnabled);
```
- [ ] revise

2021-07-27 07:57 UTC, matkatmusic commented on main.cpp
> +}
skip the if/else:
```
return preProcessedAudioLevelLeft >= audioInputClippingThreshold;
```
- [ ] revise

2021-07-27 23:54 UTC, transistasis commented on main.cpp
> +}
My intention was to emulate a hex string (without actually having converted the decimal values to hex) like in the second example. I went ahead and added spaces anyways for the added practice.

2021-07-27 23:59 UTC, transistasis commented on main.cpp
> +    };
Wow! This has been fixed.

2021-07-28 00:45 UTC, transistasis commented on main.cpp
> +}
Nice, that really simplifies things. Fixed.

2021-07-28 00:54 UTC, transistasis commented on main.cpp
> +}
More great insight. I went ahead and used the ternary expression.

2021-07-28 05:49 UTC, matkatmusic approved these changes

2021-07-28 05:50 UTC, merged